### PR TITLE
Custom maps with custom tags not showing up fix

### PR DESCRIPTION
**Pull request by nukeulater**
New chatbox commands ($maxplayers <value> and $setfov <value>) and run chatbox hooks by default
Fixed Infection wepon pick-up due to fact that Deinitialize wasn't enabling PatchWeaponsInteraction
Fixed HitFix not running on dedicated server + added more weapons

### CODE REVIEW

**Comment by iSupersniper** [comment]
There seem to be no merge conflicts in the sense of code overwrites, however has this been tested in game to verify there are no noticeable crashes?

**Comment by Himanshu-01** [comment]
Lets do a final Test then?

**Comment by nukeulater** [comment]
Ok so i forgot something and i added in a second commit, now everything works/no crashes.

**Comment by shayaantx** [comment]
tweek approved these changes, god bless him

**Pull request merged**
