### PR TITLE
More spring cleaning

### PR DESCRIPTION
**Pull request by Berthalamew**
- not done yet

### CODE REVIEW

**Comment by nukeulater** [comment]
I don't agree with most of these changes and I don't have time to review everything, please focus **strictly** on functionality changes like implementing new features or bug-fixing. Any PR "refactor" related will be closed, and as discussed on Discord, most of these changes are pointless or bring little benefit over what we currently have. And if you really need to "refactor" something, please elaborate in each commit description how the variant Y of the code X is better than X while keeping the refactor context-dependent sort of speak.

**Comment by nukeulater** [comment]
Context-dependent: i.e you're going to open one pull request to refactor/cleanup the tag definitions for example. And @Kantanomo has to agree on all of these changes as well.

**Comment by nukeulater** [comment]
Also from now on the commit descriptions should follow the format I have been using for some time now (lower case). Avoid using any off-topic crap like `blame bertha`, `blame X` I have seen in some other commit descriptions previously and so on or your PR will be closed, unless you can convince @pnill to merge it (lol).

Edit: mentioning something that uses capital letters is allowed (e.g. `XnIp` etc.)

Hopefully I have been clear enough, for any further clarifications use this PR's comment section.

**Comment by Berthalamew** [comment]
What about PRs for reimplimenting functionality that will be used for other features, ex object_new and the functions called by it which will later be used on coop.

**Comment by nukeulater** [comment]
That falls into the functionality category, if the code is decent, doesn't break anything and is functional it can be merged.

**Pull request closed without merging**
