### PR TITLE
Bug Fixes:

### PR DESCRIPTION
**Pull request by iSupersniper**
-Fixes config files to work with native windows text editor.
(Did not touch h2customlanguage.ini file yet)
-Changed version number to 4.0.3

### CODE REVIEW

**Comment by KILLER-CHIEF** [comment]
You committed to the wrong branch. Please commit to Development not a historic release branch.

**Comment by iSupersniper** [comment]
I committed here because this is just a bug fix for the latest release code, the development branch contains unstable and unfinished code for the next major release.

Why is this the wrong branch?

**Comment by KILLER-CHIEF** [comment]
The development branch contains unreleased code. The idea behind these *historic* release branches is to document what commits were in what update so no one complains about something 'y' used to work in 'x' update and none of us can remember the commit that was at that update so we can check what might of broken 'y'.

**Comment by iSupersniper** [comment]
How would i properly submit a pull request as a hotfix for the current release without including unstable code in the development branch?

**Comment by KILLER-CHIEF** [comment]
Is it a hotfix or borked code then? Your giving me mixed messages. I saw you doing some tests in Dev Preview so i assume it works good and so it would go in Development. If it were to be some new unfinished feature that has plans to be in some future release it's to go in a new branch or your own repo until it is done and ready to be integrated into Development.

Also don't change the project version number. That commit should be reserved for the moment the Development branch is going to or is ready for release. Doing it that way will also help/notify any Dev Preview members with an outdated unofficial version when trying to login after the new release dropped.

**Comment by iSupersniper** [comment]
Well, it's a hotfix to the current release to allow native windows text editors to read the config files properly.

**Pull request closed without merging**
