### PR TITLE
Keep it consistent

### PR DESCRIPTION
**Pull request by GXTX**
Looks ugly tbh (^:

### CODE REVIEW

**Comment by bigtweekx** [comment]
nah

**Comment by iSupersniper** [comment]
Nah

**Comment by num0005** [comment]
@KILLER-CHIEF

**Comment by KILLER-CHIEF** [comment]
Next time you have a tiny little style change idea, just tell one of us. I'll keep > but i'm editing the remove button to a - to keep things more consistent to my gut feeling of a style.

**Pull request closed without merging**
